In [96]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC

In [97]:
loanData=pd.read_csv(r"D:\target\ml\loanPrediction\playground-series-s4e10\train.csv")

In [98]:
loanData.head()

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,0,37,35000,RENT,0.0,EDUCATION,B,6000,11.49,0.17,N,14,0
1,1,22,56000,OWN,6.0,MEDICAL,C,4000,13.35,0.07,N,2,0
2,2,29,28800,OWN,8.0,PERSONAL,A,6000,8.90,0.21,N,10,0
3,3,30,70000,RENT,14.0,VENTURE,B,12000,11.11,0.17,N,5,0
4,4,22,60000,RENT,2.0,MEDICAL,A,6000,6.92,0.10,N,3,0

In [99]:
loanData.shape

(58645, 13)

In [100]:
loanData.describe()

,id,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,loan_status
count,58645.000000,58645.000000,5.864500e+04,58645.000000,58645.000000,58645.000000,58645.000000,58645.000000,58645.000000
mean,29322.000000,27.550857,6.404617e+04,4.701015,9217.556518,10.677874,0.159238,5.813556,0.142382
std,16929.497605,6.033216,3.793111e+04,3.959784,5563.807384,3.034697,0.091692,4.029196,0.349445
min,0.000000,20.000000,4.200000e+03,0.000000,500.000000,5.420000,0.000000,2.000000,0.000000
25%,14661.000000,23.000000,4.200000e+04,2.000000,5000.000000,7.880000,0.090000,3.000000,0.000000
50%,29322.000000,26.000000,5.800000e+04,4.000000,8000.000000,10.750000,0.140000,4.000000,0.000000
75%,43983.000000,30.000000,7.560000e+04,7.000000,12000.000000,12.990000,0.210000,8.000000,0.000000
max,58644.000000,123.000000,1.900000e+06,123.000000,35000.000000,23.220000,0.830000,30.000000,1.000000

In [101]:
loanData['loan_status'].value_counts()

loan_status
0    50295
1     8350
Name: count, dtype: int64

In [102]:
house_num={
    'RENT':0,
    'OWN':1,
    'MORTGAGE':2,
    'OTHER':3
}
loanData['person_home_ownership']=loanData['person_home_ownership'].replace(house_num)
loanData['person_home_ownership'].head()

C:\Users\Asus\AppData\Local\Temp\ipykernel_37500\1093825101.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  loanData['person_home_ownership']=loanData['person_home_ownership'].replace(house_num)

0    0
1    1
2    1
3    0
4    0
Name: person_home_ownership, dtype: int64

In [103]:
loan_intent_num={
    'DEBTCONSOLIDATION':0,
    'PERSONAL':1,
    'EDUCATION':2,
    'MEDICAL':3,
    'VENTURE':4,
    'HOMEIMPROVEMENT':5,

}
loanData['loan_intent']=loanData['loan_intent'].replace(loan_intent_num)
loanData['loan_intent'].head()

C:\Users\Asus\AppData\Local\Temp\ipykernel_37500\1465275522.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  loanData['loan_intent']=loanData['loan_intent'].replace(loan_intent_num)

0    2
1    3
2    1
3    4
4    3
Name: loan_intent, dtype: int64

In [104]:
loan_grade_num={
    'A':0,
    'B':1,
    'C':2,
    'D':3,
    'E':4,
    'F':5,
    'G':6,


}
loanData['loan_grade']=loanData['loan_grade'].replace(loan_grade_num)
loanData['loan_grade'].head()

C:\Users\Asus\AppData\Local\Temp\ipykernel_37500\1511410089.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  loanData['loan_grade']=loanData['loan_grade'].replace(loan_grade_num)

0    1
1    2
2    0
3    1
4    0
Name: loan_grade, dtype: int64

In [105]:
cb_person_default_on_file_num={
   'Y':0,
    'N':1,


}
loanData['cb_person_default_on_file']=loanData['cb_person_default_on_file'].replace(cb_person_default_on_file_num)
loanData['cb_person_default_on_file'].head()

C:\Users\Asus\AppData\Local\Temp\ipykernel_37500\1567296823.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  loanData['cb_person_default_on_file']=loanData['cb_person_default_on_file'].replace(cb_person_default_on_file_num)

0    1
1    1
2    1
3    1
4    1
Name: cb_person_default_on_file, dtype: int64

In [106]:
# loanData=loanData.drop(columns='id',axis=1)
loanData.head()

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,0,37,35000,0,0.0,2,1,6000,11.49,0.17,1,14,0
1,1,22,56000,1,6.0,3,2,4000,13.35,0.07,1,2,0
2,2,29,28800,1,8.0,1,0,6000,8.90,0.21,1,10,0
3,3,30,70000,0,14.0,4,1,12000,11.11,0.17,1,5,0
4,4,22,60000,0,2.0,3,0,6000,6.92,0.10,1,3,0

In [107]:
print(loanData.groupby('loan_status').mean())

                       id  person_age  person_income  person_home_ownership  \
loan_status
0            29378.138682   27.553634   66672.867720               0.994115
1            28983.856886   27.534132   48224.661796               0.365749

             person_emp_length  loan_intent  loan_grade     loan_amnt  \
loan_status
0                     4.863048     2.382185    0.902137   8888.883229
1                     3.725030     2.274491    2.057485  11197.271856

             loan_int_rate  loan_percent_income  cb_person_default_on_file  \
loan_status
0                10.258767             0.145105                   0.878696
1                13.202305             0.244363                   0.688503

             cb_person_cred_hist_length
loan_status
0                              5.818531
1                              5.783593

In [108]:
X=loanData.drop(columns='loan_status',axis=1)
Y=loanData['loan_status']

In [109]:
loanData_test=pd.read_csv(r"D:\target\ml\loanPrediction\playground-series-s4e10\test.csv")

In [110]:
loanData_test.shape

(39098, 12)

In [111]:
loanData_test.head()

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,58645,23,69000,RENT,3.0,HOMEIMPROVEMENT,F,25000,15.76,0.36,N,2
1,58646,26,96000,MORTGAGE,6.0,PERSONAL,C,10000,12.68,0.10,Y,4
2,58647,26,30000,RENT,5.0,VENTURE,E,4000,17.19,0.13,Y,2
3,58648,33,50000,RENT,4.0,DEBTCONSOLIDATION,A,7000,8.90,0.14,N,7
4,58649,26,102000,MORTGAGE,8.0,HOMEIMPROVEMENT,D,15000,16.32,0.15,Y,4

In [112]:
house_num={
    'RENT':0,
    'OWN':1,
    'MORTGAGE':2,
    'OTHER':3
}
loanData_test['person_home_ownership']=loanData_test['person_home_ownership'].replace(house_num)
cb_person_default_on_file_num={
   'Y':0,
    'N':1,


}
loanData_test['cb_person_default_on_file']=loanData_test['cb_person_default_on_file'].replace(cb_person_default_on_file_num)
loan_grade_num={
    'A':0,
    'B':1,
    'C':2,
    'D':3,
    'E':4,
    'F':5,
    'G':6,


}
loanData_test['loan_grade']=loanData_test['loan_grade'].replace(loan_grade_num)
loan_intent_num={
    'DEBTCONSOLIDATION':0,
    'PERSONAL':1,
    'EDUCATION':2,
    'MEDICAL':3,
    'VENTURE':4,
    'HOMEIMPROVEMENT':5,

}
loanData_test['loan_intent']=loanData_test['loan_intent'].replace(loan_intent_num)

loanData_test.head()

C:\Users\Asus\AppData\Local\Temp\ipykernel_37500\2816805583.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  loanData_test['person_home_ownership']=loanData_test['person_home_ownership'].replace(house_num)
C:\Users\Asus\AppData\Local\Temp\ipykernel_37500\2816805583.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  loanData_test['cb_person_default_on_file']=loanData_test['cb_person_default_on_file'].replace(cb_person_default_on_file_num)
C:\Users\Asus\AppData\Local\Temp\ipykernel_37500\2816805583.py:26: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  loanData_test['loan_grade']=loanData_test['loan_grade'].replace(loan_grade_num)
C:\Users\Asus\AppData\Local\Temp\ipykernel_37500\2816805583.py:36: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  loanData_test['loan_intent']=loanData_test['loan_intent'].replace(loan_intent_num)

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,58645,23,69000,0,3.0,5,5,25000,15.76,0.36,1,2
1,58646,26,96000,2,6.0,1,2,10000,12.68,0.10,0,4
2,58647,26,30000,0,5.0,4,4,4000,17.19,0.13,0,2
3,58648,33,50000,0,4.0,0,0,7000,8.90,0.14,1,7
4,58649,26,102000,2,8.0,5,3,15000,16.32,0.15,0,4

In [113]:
loanData_test.shape

(39098, 12)

In [114]:

import pandas as pd
import lightgbm as lgb
from catboost import CatBoostClassifier
from sklearn.ensemble import VotingClassifier



# For the test set, extract features (excluding 'id')
X_test = loanData_test.copy()

# LightGBM model
params = {
    'objective': 'binary',
    'boosting_type': 'gbdt',
    'metric': 'binary_error',  # Binary classification
    'num_leaves': 31,          # Controls the complexity of the model
    'learning_rate': 0.05,     # Lower learning rate for better accuracy
    'feature_fraction': 0.8     # Use a subset of features for each iteration
}
lgb_model = lgb.LGBMClassifier(**lgb_params)

# CatBoost model
catboost_params = {
    'iterations': 1000,
    'learning_rate': 0.05,
    'depth': 6,
    'loss_function': 'Logloss',
    'eval_metric': 'Accuracy',
    'early_stopping_rounds': 100
}
catboost_model = CatBoostClassifier(**catboost_params, verbose=0)

# Create the ensemble model using VotingClassifier (soft voting for probabilities)
ensemble_model = VotingClassifier(
    estimators=[('lgb', lgb_model), ('catboost', catboost_model)],
    voting='soft'  # Soft voting to average probabilities
)

# Train the ensemble model on the full training data
ensemble_model.fit(X, Y)

# Predict on the test set using the ensemble model
y_pred = ensemble_model.predict(X_test)

# Create a DataFrame with the test 'id' and predicted 'loan_status'
submission_df = pd.DataFrame({
    'id':loanData_test['id'],
    'loan_status': y_pred
})

# Save predictions to a CSV file
submission_df.to_csv('predicted_loan_status_Using_Ensemble.csv', index=False)

print("Ensemble prediction complete and saved to 'predicted_loan_status_Using_Ensemble.csv'")

[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Info] Number of positive: 8350, number of negative: 50295
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000479 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1098
[LightGBM] [Info] Number of data points in the train set: 58645, number of used features: 12
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.142382 -> initscore=-1.795644
[LightGBM] [Info] Start training from score -1.795644
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
Ensemble prediction complete and saved to 'predicted_loan_status_Using_Ensemble.csv'