In [87]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC

In [88]:
loanData=pd.read_csv(r"D:\target\ml\loanPrediction\playground-series-s4e10\train.csv")

In [89]:
loanData.head()

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,0,37,35000,RENT,0.0,EDUCATION,B,6000,11.49,0.17,N,14,0
1,1,22,56000,OWN,6.0,MEDICAL,C,4000,13.35,0.07,N,2,0
2,2,29,28800,OWN,8.0,PERSONAL,A,6000,8.90,0.21,N,10,0
3,3,30,70000,RENT,14.0,VENTURE,B,12000,11.11,0.17,N,5,0
4,4,22,60000,RENT,2.0,MEDICAL,A,6000,6.92,0.10,N,3,0

In [90]:
loanData.shape

(58645, 13)

In [91]:
loanData.describe()

,id,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,loan_status
count,58645.000000,58645.000000,5.864500e+04,58645.000000,58645.000000,58645.000000,58645.000000,58645.000000,58645.000000
mean,29322.000000,27.550857,6.404617e+04,4.701015,9217.556518,10.677874,0.159238,5.813556,0.142382
std,16929.497605,6.033216,3.793111e+04,3.959784,5563.807384,3.034697,0.091692,4.029196,0.349445
min,0.000000,20.000000,4.200000e+03,0.000000,500.000000,5.420000,0.000000,2.000000,0.000000
25%,14661.000000,23.000000,4.200000e+04,2.000000,5000.000000,7.880000,0.090000,3.000000,0.000000
50%,29322.000000,26.000000,5.800000e+04,4.000000,8000.000000,10.750000,0.140000,4.000000,0.000000
75%,43983.000000,30.000000,7.560000e+04,7.000000,12000.000000,12.990000,0.210000,8.000000,0.000000
max,58644.000000,123.000000,1.900000e+06,123.000000,35000.000000,23.220000,0.830000,30.000000,1.000000

In [92]:
loanData['loan_status'].value_counts()

loan_status
0    50295
1     8350
Name: count, dtype: int64

In [93]:
house_num={
    'RENT':0,
    'OWN':1,
    'MORTGAGE':2,
    'OTHER':3
}
loanData['person_home_ownership']=loanData['person_home_ownership'].replace(house_num)
loanData['person_home_ownership'].head()

0    0
1    1
2    1
3    0
4    0
Name: person_home_ownership, dtype: int64

In [94]:
loan_intent_num={
    'DEBTCONSOLIDATION':0,
    'PERSONAL':1,
    'EDUCATION':2,
    'MEDICAL':3,
    'VENTURE':4,
    'HOMEIMPROVEMENT':5,

}
loanData['loan_intent']=loanData['loan_intent'].replace(loan_intent_num)
loanData['loan_intent'].head()

0    2
1    3
2    1
3    4
4    3
Name: loan_intent, dtype: int64

In [95]:
loan_grade_num={
    'A':0,
    'B':1,
    'C':2,
    'D':3,
    'E':4,
    'F':5,
    'G':6,


}
loanData['loan_grade']=loanData['loan_grade'].replace(loan_grade_num)
loanData['loan_grade'].head()

0    1
1    2
2    0
3    1
4    0
Name: loan_grade, dtype: int64

In [96]:
cb_person_default_on_file_num={
   'Y':0,
    'N':1,


}
loanData['cb_person_default_on_file']=loanData['cb_person_default_on_file'].replace(cb_person_default_on_file_num)
loanData['cb_person_default_on_file'].head()

0    1
1    1
2    1
3    1
4    1
Name: cb_person_default_on_file, dtype: int64

In [97]:
# loanData=loanData.drop(columns='id',axis=1)
loanData.head()

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,0,37,35000,0,0.0,2,1,6000,11.49,0.17,1,14,0
1,1,22,56000,1,6.0,3,2,4000,13.35,0.07,1,2,0
2,2,29,28800,1,8.0,1,0,6000,8.90,0.21,1,10,0
3,3,30,70000,0,14.0,4,1,12000,11.11,0.17,1,5,0
4,4,22,60000,0,2.0,3,0,6000,6.92,0.10,1,3,0

In [98]:
print(loanData.groupby('loan_status').mean())

                       id  person_age  person_income  person_home_ownership  \
loan_status
0            29378.138682   27.553634   66672.867720               0.994115
1            28983.856886   27.534132   48224.661796               0.365749

             person_emp_length  loan_intent  loan_grade     loan_amnt  \
loan_status
0                     4.863048     2.382185    0.902137   8888.883229
1                     3.725030     2.274491    2.057485  11197.271856

             loan_int_rate  loan_percent_income  cb_person_default_on_file  \
loan_status
0                10.258767             0.145105                   0.878696
1                13.202305             0.244363                   0.688503

             cb_person_cred_hist_length
loan_status
0                              5.818531
1                              5.783593

In [99]:
X=loanData.drop(columns='loan_status',axis=1)
Y=loanData['loan_status']

In [100]:
loanData_test=pd.read_csv(r"D:\target\ml\loanPrediction\playground-series-s4e10\test.csv")

In [101]:
loanData_test.shape

(39098, 12)

In [102]:
loanData_test.head()

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,58645,23,69000,RENT,3.0,HOMEIMPROVEMENT,F,25000,15.76,0.36,N,2
1,58646,26,96000,MORTGAGE,6.0,PERSONAL,C,10000,12.68,0.10,Y,4
2,58647,26,30000,RENT,5.0,VENTURE,E,4000,17.19,0.13,Y,2
3,58648,33,50000,RENT,4.0,DEBTCONSOLIDATION,A,7000,8.90,0.14,N,7
4,58649,26,102000,MORTGAGE,8.0,HOMEIMPROVEMENT,D,15000,16.32,0.15,Y,4

In [103]:
house_num={
    'RENT':0,
    'OWN':1,
    'MORTGAGE':2,
    'OTHER':3
}
loanData_test['person_home_ownership']=loanData_test['person_home_ownership'].replace(house_num)
cb_person_default_on_file_num={
   'Y':0,
    'N':1,


}
loanData_test['cb_person_default_on_file']=loanData_test['cb_person_default_on_file'].replace(cb_person_default_on_file_num)
loan_grade_num={
    'A':0,
    'B':1,
    'C':2,
    'D':3,
    'E':4,
    'F':5,
    'G':6,


}
loanData_test['loan_grade']=loanData_test['loan_grade'].replace(loan_grade_num)
loan_intent_num={
    'DEBTCONSOLIDATION':0,
    'PERSONAL':1,
    'EDUCATION':2,
    'MEDICAL':3,
    'VENTURE':4,
    'HOMEIMPROVEMENT':5,

}
loanData_test['loan_intent']=loanData_test['loan_intent'].replace(loan_intent_num)

loanData_test.head()

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,58645,23,69000,0,3.0,5,5,25000,15.76,0.36,1,2
1,58646,26,96000,2,6.0,1,2,10000,12.68,0.10,0,4
2,58647,26,30000,0,5.0,4,4,4000,17.19,0.13,0,2
3,58648,33,50000,0,4.0,0,0,7000,8.90,0.14,1,7
4,58649,26,102000,2,8.0,5,3,15000,16.32,0.15,0,4

In [104]:
loanData_test.shape

(39098, 12)

In [105]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [106]:
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X, Y)

RandomForestClassifier(random_state=42)

In [107]:
# Predict the target values for the test dataset
X_test = loanData_test # Use the entire test set as features
test_predictions = rf_model.predict(X_test)

In [114]:
# Assuming 'test_data' is your test DataFrame that contains the 'id' column
predictions_df = pd.DataFrame({
    'id': loanData_test['id'],  # Use 'id' column from the test dataset
    'loan_status': test_predictions  # Use the predictions generated by the model
})

# Export to CSV
predictions_df.to_csv('test_predictions.csv', index=False)